/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rain_ndk_JniPrint */

#ifndef _Included_com_rain_ndk_JniPrint
#define _Included_com_rain_ndk_JniPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rain_ndk_JniPrint
 * Method:    printInput
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_rain_ndk_JniPrint_printInput
  (JNIEnv *env, jclass cls, jstring str);

#ifdef __cplusplus
}
#endif
#endif
